import { count } from "drizzle-orm";
import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { catches } from "./schema";
import type * as schema from "./schema";
import { seasonFromDate, timeOfDayFromDate } from "../time";
import { inferHabitat } from "../habitat";
import type { CatchInput } from "../types";

const SEED: CatchInput[] = [
  {
    photoPath: "/seed/largemouth.svg",
    species: "Largemouth Bass",
    speciesSuggested: "Largemouth Bass",
    speciesConfidence: 0.91,
    speciesSource: "demo",
    latitude: 30.388,
    longitude: -97.975,
    placeName: "Lake Travis, TX",
    temperatureF: 88,
    weatherCondition: "clear",
    windSpeedMph: 6,
    precipitationIn: 0,
    humidity: 48,
    caughtAt: "2025-07-12T15:40:00-05:00",
    timeOfDay: "afternoon",
    season: "summer",
    bait: "Texas-rigged worm",
    waterClarity: "stained",
    notes: "Shade line on the main-lake point. Fish smashed it on the pause.",
  },
  {
    photoPath: "/seed/largemouth.svg",
    species: "Largemouth Bass",
    speciesSuggested: "Largemouth Bass",
    speciesConfidence: 0.88,
    speciesSource: "demo",
    latitude: 30.391,
    longitude: -97.972,
    placeName: "Lake Travis, TX",
    temperatureF: 74,
    weatherCondition: "fog",
    windSpeedMph: 2,
    precipitationIn: 0,
    humidity: 86,
    caughtAt: "2025-07-13T06:10:00-05:00",
    timeOfDay: "dawn",
    season: "summer",
    bait: "Topwater walking bait",
    waterClarity: "stained",
    notes: "Dawn fog, slick calm. Same point as yesterday afternoon.",
  },
  {
    photoPath: "/seed/rainbow.svg",
    species: "Rainbow Trout",
    speciesSuggested: "Rainbow Trout",
    speciesConfidence: 0.86,
    speciesSource: "demo",
    latitude: 39.368,
    longitude: -106.818,
    placeName: "Frying Pan River, CO",
    temperatureF: 48,
    weatherCondition: "cloudy",
    windSpeedMph: 8,
    precipitationIn: 0,
    humidity: 62,
    caughtAt: "2025-04-18T09:20:00-06:00",
    timeOfDay: "morning",
    season: "spring",
    bait: "RS2, size 20",
    waterClarity: "clear",
    notes: "Tailwater nymphing below the dam. Cloudy and cool — they were eating.",
  },
  {
    photoPath: "/seed/rainbow.svg",
    species: "Rainbow Trout",
    speciesSuggested: "Rainbow Trout",
    speciesConfidence: 0.79,
    speciesSource: "demo",
    latitude: 39.37,
    longitude: -106.82,
    placeName: "Frying Pan River, CO",
    temperatureF: 52,
    weatherCondition: "overcast",
    windSpeedMph: 10,
    precipitationIn: 0.05,
    humidity: 78,
    caughtAt: "2025-10-03T08:45:00-06:00",
    timeOfDay: "morning",
    season: "fall",
    bait: "Pheasant tail",
    waterClarity: "clear",
    notes: "Light drizzle, fall BWO hint. Same run as April.",
  },
  {
    photoPath: "/seed/redfish.svg",
    species: "Redfish",
    speciesSuggested: "Redfish",
    speciesConfidence: 0.84,
    speciesSource: "demo",
    latitude: 28.738,
    longitude: -80.755,
    placeName: "Mosquito Lagoon, FL",
    temperatureF: 82,
    weatherCondition: "partly-cloudy",
    windSpeedMph: 12,
    precipitationIn: 0,
    humidity: 71,
    caughtAt: "2025-08-21T19:05:00-04:00",
    timeOfDay: "dusk",
    season: "summer",
    bait: "Gold spoon",
    tide: "incoming",
    waterClarity: "stained",
    notes: "Tailing on the flood. Wind enough to ripple the flat.",
  },
  {
    photoPath: "/seed/speckled.svg",
    species: "Speckled Trout",
    speciesSuggested: "Speckled Trout",
    speciesConfidence: 0.73,
    speciesSource: "demo",
    latitude: 28.741,
    longitude: -80.752,
    placeName: "Mosquito Lagoon, FL",
    temperatureF: 80,
    weatherCondition: "clear",
    windSpeedMph: 8,
    precipitationIn: 0,
    humidity: 68,
    caughtAt: "2025-08-22T19:20:00-04:00",
    timeOfDay: "dusk",
    season: "summer",
    bait: "Soft plastic on jighead",
    tide: "high",
    waterClarity: "stained",
    notes: "Next evening, same flat. Clearer sky, slightly less wind.",
  },
  {
    photoPath: "/seed/bluegill.svg",
    species: "Bluegill",
    speciesSuggested: "Bluegill",
    speciesConfidence: 0.9,
    speciesSource: "demo",
    latitude: 40.212,
    longitude: -82.891,
    placeName: "Farm Pond, OH",
    temperatureF: 79,
    weatherCondition: "clear",
    windSpeedMph: 4,
    precipitationIn: 0,
    humidity: 52,
    caughtAt: "2025-06-08T14:15:00-04:00",
    timeOfDay: "afternoon",
    season: "summer",
    bait: "Popper",
    waterClarity: "clear",
    notes: "Beds still visible. Kids' pond, but they were chewing.",
  },
  {
    photoPath: "/seed/largemouth.svg",
    species: "Largemouth Bass",
    speciesSuggested: "Largemouth Bass",
    speciesConfidence: 0.8,
    speciesSource: "demo",
    latitude: 40.213,
    longitude: -82.89,
    placeName: "Farm Pond, OH",
    temperatureF: 76,
    weatherCondition: "cloudy",
    windSpeedMph: 5,
    precipitationIn: 0,
    humidity: 61,
    caughtAt: "2025-06-22T15:05:00-04:00",
    timeOfDay: "afternoon",
    season: "summer",
    bait: "Senko",
    waterClarity: "clear",
    notes: "Same pond two weeks later. Overcast summer afternoon, bass under the dock shade.",
  },
  {
    photoPath: "/seed/walleye.svg",
    species: "Walleye",
    speciesSuggested: "Walleye",
    speciesConfidence: 0.77,
    speciesSource: "demo",
    latitude: 41.541,
    longitude: -81.635,
    placeName: "Lake Erie, OH",
    temperatureF: 55,
    weatherCondition: "cloudy",
    windSpeedMph: 15,
    precipitationIn: 0,
    humidity: 64,
    caughtAt: "2025-05-02T19:40:00-04:00",
    timeOfDay: "dusk",
    season: "spring",
    bait: "Worm harness",
    waterClarity: "stained",
    notes: "Chop on the water, spring troll along the 28-foot break.",
  },
  {
    photoPath: "/seed/striper.svg",
    species: "Striped Bass",
    speciesSuggested: "Striped Bass",
    speciesConfidence: 0.82,
    speciesSource: "demo",
    latitude: 38.975,
    longitude: -76.247,
    placeName: "Chesapeake Bay, MD",
    temperatureF: 58,
    weatherCondition: "overcast",
    windSpeedMph: 9,
    precipitationIn: 0,
    humidity: 74,
    caughtAt: "2025-10-19T06:25:00-04:00",
    timeOfDay: "dawn",
    season: "fall",
    bait: "Bucktail jig",
    tide: "outgoing",
    waterClarity: "murky",
    notes: "Fall dawn, outgoing tide at the channel edge.",
  },
  {
    photoPath: "/seed/rainbow.svg",
    species: "Brown Trout",
    speciesSuggested: "Brown Trout",
    speciesConfidence: 0.74,
    speciesSource: "demo",
    latitude: 39.365,
    longitude: -106.821,
    placeName: "Frying Pan River, CO",
    temperatureF: 34,
    weatherCondition: "overcast",
    windSpeedMph: 6,
    precipitationIn: 0,
    humidity: 71,
    caughtAt: "2026-01-11T10:05:00-07:00",
    timeOfDay: "morning",
    season: "winter",
    bait: "San Juan worm",
    waterClarity: "clear",
    notes: "Winter tailwater. Slow and deep, overcast and raw.",
  },
  {
    photoPath: "/seed/mahi.svg",
    species: "Mahi-mahi",
    speciesSuggested: "Mahi-mahi",
    speciesConfidence: 0.81,
    speciesSource: "demo",
    latitude: 25.76,
    longitude: -80.02,
    placeName: "Gulf Stream, FL",
    temperatureF: 84,
    weatherCondition: "clear",
    windSpeedMph: 11,
    precipitationIn: 0,
    humidity: 66,
    caughtAt: "2025-07-28T14:20:00-04:00",
    timeOfDay: "afternoon",
    season: "summer",
    bait: "Ballyhoo trolling",
    waterClarity: "clear",
    notes: "Weed line in the blue water. Color lit up on the second teaser.",
  },
];

export function seedIfEmpty(db: BetterSQLite3Database<typeof schema>, ownerId: string) {
  const row = db.select({ n: count() }).from(catches).get();
  if ((row?.n ?? 0) > 0) return;

  const stamp = new Date().toISOString();
  for (const item of SEED) {
    const caught = new Date(item.caughtAt);
    db.insert(catches)
      .values({
        id: crypto.randomUUID(),
        photoPath: item.photoPath ?? null,
        species: item.species,
        speciesSuggested: item.speciesSuggested ?? null,
        speciesConfidence: item.speciesConfidence ?? null,
        speciesSource: item.speciesSource ?? "demo",
        latitude: item.latitude ?? null,
        longitude: item.longitude ?? null,
        placeName: item.placeName ?? null,
        temperatureF: item.temperatureF ?? null,
        weatherCondition: item.weatherCondition ?? null,
        windSpeedMph: item.windSpeedMph ?? null,
        precipitationIn: item.precipitationIn ?? null,
        humidity: item.humidity ?? null,
        caughtAt: caught.toISOString(),
        timeOfDay: item.timeOfDay ?? timeOfDayFromDate(caught),
        season: item.season ?? seasonFromDate(caught),
        notes: item.notes ?? null,
        bait: item.bait ?? null,
        tide: item.tide ?? null,
        waterClarity: item.waterClarity ?? null,
        habitat: item.habitat ?? inferHabitat(item.species),
        anglerId: ownerId,
        sharedWithLinked: 0,
        createdAt: stamp,
        updatedAt: stamp,
      })
      .run();
  }
}
